### ISSUE TITLE
Improve integration test line84

### ISSUE THREAD

**Issue by stefania11** [learn-co-curriculum/oo-jukebox#6]
(line 80..85) 
 context 'with a song as an argument' do
        it 'can take a human-readable index' do
          jukebox.stub(:gets).and_return('play 1', 'exit')
          play_with_song_name_output = capture_stdout { jukebox.call }
          expect(play_with_song_name_output).to match(/Now Playing: Phoenix - 1901/)
        end

I don't think this particular test is enabling us to find an abstract solution as we have to hardcode something like 
    formated_choice = choice.split(" ")
    play(formated_choice[1])

However this does not account for queries like '1 play', '1 song' etc.

**Comment by AnnJohn** [comment]
@SophieDeBenedetto check in September 3

**Comment by SophieDeBenedetto** [comment]
Hi @stefania11, I'm closing this issue because this lab has been improved and the test you are referring to has been deprecated.
